version: '3.8'

services:
  # Production build with nginx
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "38107:80"
    container_name: test-appid-pay-example
    restart: unless-stopped
