version: '3.8'

services:
  # Production build with nginx
  app:
    image: primuslabs/test-appid-pay-example:latest
    ports:
      - "38108:80"
    container_name: test-appid-pay-example
    restart: unless-stopped
